replicaCount: 1

image:
  repository: "helmchart"
  tag: "v1"
  pullPolicy: IfNotPresent

deployment:
  name: helmchart
  port: 8080

service:
  name: helmchart
  type: NodePort
  port: 8080
  nodePort: 31000

resources:
  limits:
    # Since the Spring Boot Maven Plugin builds our containers via the Java Buildpack, we need around
    # 650 MB, otherwise the container fails to start with: "allocated memory is greater..."
    # https://twitter.com/nebhale/status/1281646532295454720
    # In exchange, we get the JVM set up with best practice settings in memory regions.
    # Hopefully getting less trouble with ops.
    # https://www.cloudfoundry.org/blog/just-released-java-buildpack-4-0/
    # Depending on the number of classes in our apps we might have to increase this later.
    memory: 650Mi
  requests:
    memory: 650Mi